CREATE TABLE CustomerOrder 
(
cargoinvoice NVARCHAR(50) COLLATE Cyrillic_General_CI_AS, 
client INT, 
clientNameEn NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
clientNameRu NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
consignee INT, 
consigneeNameEn NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
consigneeNameRu NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
employe NVARCHAR(10) COLLATE Cyrillic_General_CI_AS, 
employeName NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
flowtype INT, 
flowtypeName NVARCHAR(50) COLLATE Cyrillic_General_CI_AS, 
id bigint, 
import NVARCHAR(10) COLLATE Cyrillic_General_CI_AS, 
model NVARCHAR(10) COLLATE Cyrillic_General_CI_AS, 
modelNameEn NVARCHAR(25) COLLATE Cyrillic_General_CI_AS, 
modelNameRu NVARCHAR(25) COLLATE Cyrillic_General_CI_AS, 
orderDate DATETIME, 
orderDescription NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
orderDescription1 NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
orderDescription2 NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
orderLdm INT, 
orderNo NVARCHAR(20) COLLATE Cyrillic_General_CI_AS, 
orderNumber NVARCHAR(20) COLLATE Cyrillic_General_CI_AS, 
orderParcels INT, orderPlanDateFrom DATETIME, 
orderPlanDateTo DATETIME, 
orderPrice DECIMAL(18,0), 
orderPriority NVARCHAR(25) COLLATE Cyrillic_General_CI_AS, 
orderSono NVARCHAR(50) COLLATE Cyrillic_General_CI_AS, 
orderType INT, 
orderVolume DECIMAL(18,0), 
orderWeight DECIMAL(18,0), 
sender NVARCHAR(100) COLLATE Cyrillic_General_CI_AS, 
senderNameEn NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
senderNameRu NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
supplier NVARCHAR(10) COLLATE Cyrillic_General_CI_AS, 
supplierNameEn NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
supplierNameRu NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
truck NVARCHAR(10) COLLATE Cyrillic_General_CI_AS, 
truckName NVARCHAR(50) COLLATE Cyrillic_General_CI_AS, 
dtLoss DATETIME, compensatedByInsurance DECIMAL(18,0), 
notes NVARCHAR(255) COLLATE Cyrillic_General_CI_AS, 
typeId INT, 
CLMstatus BIT);